import { z } from 'zod';

export const createActivitySchema = z.object({
  workspaceId: z.string().uuid(),
  projectId: z.string().uuid().optional(),
  userId: z.string().uuid(),
  type: z.enum([
    'TASK_CREATED',
    'TASK_UPDATED',
    'TASK_DELETED',
    'TASK_ASSIGNED',
    'TASK_COMPLETED',
    'COMMENT_CREATED',
    'COMMENT_UPDATED',
    'COMMENT_DELETED',
    'PROJECT_CREATED',
    'PROJECT_UPDATED',
    'PROJECT_DELETED',
    'MEMBER_JOINED',
    'MEMBER_LEFT',
    'WORKSPACE_CREATED',
    'WORKSPACE_UPDATED',
  ]),
  entityType: z.string().min(1).max(50),
  entityId: z.string().uuid(),
  action: z.string().min(1).max(255),
  metadata: z.record(z.any()).optional(),
});

export const listActivitiesSchema = z.object({
  workspaceId: z.string().uuid().optional(),
  projectId: z.string().uuid().optional(),
  userId: z.string().uuid().optional(),
  type: z.enum([
    'TASK_CREATED',
    'TASK_UPDATED',
    'TASK_DELETED',
    'TASK_ASSIGNED',
    'TASK_COMPLETED',
    'COMMENT_CREATED',
    'COMMENT_UPDATED',
    'COMMENT_DELETED',
    'PROJECT_CREATED',
    'PROJECT_UPDATED',
    'PROJECT_DELETED',
    'MEMBER_JOINED',
    'MEMBER_LEFT',
    'WORKSPACE_CREATED',
    'WORKSPACE_UPDATED',
  ]).optional(),
  entityType: z.string().optional(),
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
  limit: z.number().int().min(1).max(100).optional(),
  offset: z.number().int().min(0).optional(),
});
